export default function Head() {
  return (
    <>
      <title>3-column preview card component solution</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/images/favicon-32x32.png" />
    </>
  )
}
